# Generated by Django 6.0.6 on 2026-07-02 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_assets', '0002_assetcategory_vendor_asset_category_assetsubcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='assetsubcategory',
            options={'verbose_name': 'Asset Sub Category', 'verbose_name_plural': 'Asset Sub Categories'},
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('assignment_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Returned', 'Returned'), ('Lost', 'Lost'), ('Transferred', 'Transferred')], default='Assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_assets.asset')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_assets.employee')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_received', to='core_assets.employee')),
            ],
        ),
    ]
