# Generated by Django 6.0.7 on 2026-07-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_assets', '0002_alter_maintenancehistory_maintenance_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalActivityLog',
        ),
    ]
