# Generated by Django 6.0.7 on 2026-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_assets', '0003_delete_historicalactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaintenancehistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
