"""
Django settings for itam_core project.
Generated by 'django-admin startproject' using Django 6.0.6.
Enhanced for Enterprise IT Asset Management System (ITAM).
"""

import os
import dj_database_url
from pathlib import Path

# ==============================================================================
# CORE CONFIGURATION
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-d8ltpn3l-jk=*bj17%kq&vn!wf=0f2p&#-w8lolf_$@nzs8en('

DEBUG = True  # প্রোডাকশনে লাইভ করার সময় এটি False করে দেবেন

ALLOWED_HOSTS = ['*']


# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'simple_history',
    'django_currentuser',

    # Authentication Framework (django-allauth)
    'allauth',
    'allauth.account',

    # Local Project Apps
    'core_assets',
]

JAZZMIN_SETTINGS = {
    "site_title": "ITAM Portal",
    "site_header": "ITAM Portal",
    "site_brand": "ITAM Infrastructure",
    "welcome_sign": "Welcome to ITAM System",
    "copyright": "ITAM Infrastructure Asset Ltd.",
    "version": "1.0.0",
    
    "search_model": ["core_assets.Asset"],
    "show_ui_builder": False,
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # এটি ডিফল্ট অ্যাপ মেনু হাইড করে আপনার কাস্টম মেনু ফোকাস করবে
    "order_with_respect_to": ["core_assets"],

    "menu": [
        {"name": "Dashboard", "url": "admin:index", "icon": "fas fa-tachometer-alt"},
        {
            "name": "Organization Master",
            "icon": "fas fa-building",
            "items": [
                "core_assets.Department",
                "core_assets.Location",
                "core_assets.Employee",
                "core_assets.Vendor",
            ],
        },
        {
            "name": "Asset Management",
            "icon": "fas fa-laptop",
            "items": [
                "core_assets.Asset",
                "core_assets.AssetCategory",
                "core_assets.AssetSubCategory",
            ],
        },
        {
            "name": "Procurement & Receiving",
            "icon": "fas fa-shopping-cart",
            "items": [
                "core_assets.PurchaseOrder",
                "core_assets.PurchaseOrderDetail",
                "core_assets.GoodsReceipt",
                "core_assets.GoodsReceiptDetail",
            ],
        },
        {
            "name": "Operations & Transfer",
            "icon": "fas fa-exchange-alt",
            "items": [
                "core_assets.AssetAssignment",
                "core_assets.AssetTransfer",
            ],
        },
        {
            "name": "Maintenance & Audit",
            "icon": "fas fa-tools",
            "models": [
                "core_assets.MaintenanceRequest",
                "core_assets.MaintenanceHistory",
                "core_assets.AssetAudit",
                "core_assets.AssetAuditDetail",
            ],
        },
        {
            "name": "Software & Disposal",
            "icon": "fas fa-trash-alt",
            "models": [
                "core_assets.SoftwareProduct",
                "core_assets.SoftwareLicense",
                "core_assets.SoftwareInstallation",
                "core_assets.AssetDisposal",
            ],
        },
        {
            "name": "System & Logs",
            "icon": "fas fa-cog",
            "models": [
                "core_assets.AssetDocument",
                "core_assets.ActivityLog",
                "auth.User",
            ],
        },
    ],

    "icons": {
        "auth.User": "fas fa-user",
        "core_assets.Department": "fas fa-building",
        "core_assets.Asset": "fas fa-laptop",
        "core_assets.PurchaseOrder": "fas fa-file-invoice-dollar",
        "core_assets.MaintenanceRequest": "fas fa-tools",
        "core_assets.SoftwareLicense": "fas fa-key",
        "core_assets.ActivityLog": "fas fa-shield-alt",
        "core_assets.MaintenanceHistory": "fas fa-history",
        "core_assets.AssetAudit": "fas fa-clipboard-check",
        "core_assets.AssetDisposal": "fas fa-trash-alt",
        "core_assets.AssetDocument": "fas fa-file-alt",
    },
}

JAZZMIN_UI_TUNER = {
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "navbar": "navbar-navy navbar-dark",
    "brand_colour": "navbar-navy",
    "accent": "accent-navy",
    "theme": "default",
    "dark_mode_theme": "darkly",
}

JAZZMIN_SETTINGS["order_with_respect_to"] = ["core_assets"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'itam_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itam_core.wsgi.application'


# ==============================================================================
# DATABASE & AUTHENTICATION BACKENDS
# ==============================================================================

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True
    )
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1


# ==============================================================================
# PASSWORD VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# STATIC & MEDIA FILES CONFIGURATION
# ==============================================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ==============================================================================
# DJANGO-ALLAUTH CONFIGURATION (FINAL)
# ==============================================================================

# Authentication settings
ACCOUNT_LOGIN_METHODS = ['email']
ACCOUNT_SIGNUP_FIELDS = ['email', 'username', 'password1', 'password2']

LOGIN_REDIRECT_URL = '/'

# ==============================================================================
# EMAIL (SMTP) CONFIGURATION
# ==============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'ITAM System <your-email@gmail.com>'

import os
from django.contrib.auth import get_user_model

# এই কোডটি শুধুমাত্র রেন্ডার সার্ভারে রান করবে
if os.environ.get('RENDER'):
    try:
        User = get_user_model()
        # আপনার সঠিক ইউজারনেম 'Ruhul_Amin' ব্যবহার করা হয়েছে
        user = User.objects.get(username='Ruhul_Amin')
        user.set_password('adminuae') # নতুন পাসওয়ার্ড
        user.save()
        print("Password reset successful!")
    except Exception as e:
        print(f"Password reset skipped: {e}")

